spring:
  config:
    import: optional:application-secret.yml
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
          ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        default_batch_fetch_size: 100
        format_sql: true
