spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 389644896984-o6ipemkoouknl69dnqc3vg3nos193r4g.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          kakao:
            client-id: 2c0333dcf1f168fe96c1f1e506e87066
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  cloud:
    azure:
      storage:
        blob:
          connection-string: "DefaultEndpointsProtocol=https;AccountName=minwoo;AccountKey=gY0ulQNDKcZGVtOiC1Uh2OiwzYLcehNzivEqjAr2GKEWkQYZlRKHeZZMqjtXALg/0BLcfFm3K1yv+AStjcQg9A==;EndpointSuffix=core.windows.net"
          container-name: "minwoo"
  datasource:
    url: jdbc:postgresql://localhost:5432/balance_game
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver

jwt:
  secret: 'dasdkqwjdiniononb123bosdjbnj123112as'
  access-token-expiration-minutes: 60 #