-- =====================================================
-- 밸런스 게임 시스템 통합 데이터베이스 초기화 스크립트
-- Version: 1.0 (Unified) - 엔티티와 완전 일치
-- Description: 실제 엔티티 클래스와 일치하는 테이블 구조
-- =====================================================

-- 1. 기본 테이블 생성
-- =====================================================

-- 주식 이미지 테이블
CREATE TABLE IF NOT EXISTS public.stock_image (
    image_id    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at  TIMESTAMP(6),
    updated_at  TIMESTAMP(6),
    image_url   VARCHAR(2048) NOT NULL,
    description VARCHAR(255),
    tags        VARCHAR(255)
);

-- 사용자 테이블
CREATE TABLE IF NOT EXISTS public."user" (
    user_id     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at  TIMESTAMP(6),
    updated_at  TIMESTAMP(6),
    nickname    VARCHAR(50)  NOT NULL UNIQUE,
    provider    VARCHAR(50),
    email       VARCHAR(255) UNIQUE,
    password    VARCHAR(255),
    provider_id VARCHAR(255),
    role        VARCHAR(255) NOT NULL,
    CONSTRAINT uk_user_provider_and_id UNIQUE (provider, provider_id)
);

-- 질문 테이블 (승인 시스템 포함)
CREATE TABLE IF NOT EXISTS public.question (
    question_id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    is_active          BOOLEAN      NOT NULL,
    created_at         TIMESTAMP(6),
    creator_id         BIGINT,
    updated_at         TIMESTAMP(6),
    keyword            VARCHAR(50),
    text               VARCHAR(500) NOT NULL,
    option_a_image_url VARCHAR(2048),
    option_b_image_url VARCHAR(2048),
    option_a_text      VARCHAR(255) NOT NULL,
    option_b_text      VARCHAR(255) NOT NULL,
    -- 승인 시스템 관련 컬럼 (엔티티 기본값에 맞춤)
    approval_status    VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    rejection_reason   VARCHAR(500),
    approved_by        BIGINT,
    approved_at        TIMESTAMP(6),
    CONSTRAINT fk_question_user FOREIGN KEY (creator_id) REFERENCES public."user"(user_id),
    CONSTRAINT fk_question_approved_by FOREIGN KEY (approved_by) REFERENCES public."user"(user_id) ON DELETE SET NULL
);

-- 질문 번들 테이블
CREATE TABLE IF NOT EXISTS public.question_bundle (
    bundle_id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    is_public   BOOLEAN      NOT NULL,
    created_at  TIMESTAMP(6),
    creator_id  BIGINT       NOT NULL,
    updated_at  TIMESTAMP(6),
    title       VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    keywords    VARCHAR(255),
    CONSTRAINT fk_bundle_user FOREIGN KEY (creator_id) REFERENCES public."user"(user_id)
);

-- 번들-질문 매핑 테이블
CREATE TABLE IF NOT EXISTS public.bundle_question (
    bundle_question_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_index        INTEGER NOT NULL,
    bundle_id          BIGINT  NOT NULL,
    question_id        BIGINT  NOT NULL,
    CONSTRAINT fk_bundle_question_bundle FOREIGN KEY (bundle_id) REFERENCES public.question_bundle(bundle_id),
    CONSTRAINT fk_bundle_question_question FOREIGN KEY (question_id) REFERENCES public.question(question_id),
    CONSTRAINT uk_bundle_question UNIQUE (bundle_id, question_id)
);

-- 게임 세션 테이블 (엔티티와 완전 일치)
CREATE TABLE IF NOT EXISTS public.game_session (
    session_id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at             TIMESTAMP(6) NOT NULL,
    bundle_id              BIGINT NOT NULL,
    -- 플레이어 관련
    player_user_id         BIGINT,
    temp_user_id           VARCHAR(50),
    -- 공유 코드 시스템
    share_code             VARCHAR(8) UNIQUE,
    share_code_created_at  TIMESTAMP(6),
    share_code_expires_at  TIMESTAMP(6),
    parent_session_id      BIGINT,
    -- 세션 상태 (엔티티에 맞춘 컬럼)
    session_status         VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    completed_at           TIMESTAMP(6),
    CONSTRAINT fk_session_bundle FOREIGN KEY (bundle_id) REFERENCES public.question_bundle(bundle_id),
    CONSTRAINT fk_game_session_player FOREIGN KEY (player_user_id) REFERENCES public."user"(user_id) ON DELETE SET NULL,
    CONSTRAINT fk_game_session_parent FOREIGN KEY (parent_session_id) REFERENCES public.game_session(session_id) ON DELETE CASCADE
);

-- 질문 통계 테이블
CREATE TABLE IF NOT EXISTS public.question_stats (
    question_id    BIGINT PRIMARY KEY,
    option_a_count BIGINT       NOT NULL DEFAULT 0,
    option_b_count BIGINT       NOT NULL DEFAULT 0,
    total_count    BIGINT       NOT NULL DEFAULT 0,
    updated_at     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stats_question FOREIGN KEY (question_id) REFERENCES public.question(question_id) ON DELETE CASCADE
);

-- 사용자 답변 테이블 (엔티티와 일치)
CREATE TABLE IF NOT EXISTS public.user_answer (
    answer_id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    selected_option VARCHAR(1) NOT NULL, -- A 또는 B (SelectedOption enum)
    answered_at     TIMESTAMP(6) NOT NULL,
    question_id     BIGINT NOT NULL,
    user_id         BIGINT,
    session_id      BIGINT NOT NULL,
    CONSTRAINT fk_answer_question FOREIGN KEY (question_id) REFERENCES public.question(question_id),
    CONSTRAINT fk_answer_user FOREIGN KEY (user_id) REFERENCES public."user"(user_id),
    CONSTRAINT fk_answer_session FOREIGN KEY (session_id) REFERENCES public.game_session(session_id)
);

-- 질문 번들 통계 테이블
CREATE TABLE IF NOT EXISTS public.question_bundle_stats (
    bundle_id  BIGINT PRIMARY KEY,
    play_count BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_bundle_stats_bundle FOREIGN KEY (bundle_id) REFERENCES public.question_bundle(bundle_id) ON DELETE CASCADE
);

-- 2. 인덱스 생성 (엔티티 @Index 어노테이션 반영)
-- =====================================================

-- 질문 관련 인덱스
CREATE INDEX IF NOT EXISTS idx_question_keyword ON public.question(keyword) WHERE keyword IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_question_is_active ON public.question(is_active);
CREATE INDEX IF NOT EXISTS idx_question_keyword_active ON public.question(keyword, is_active)
    WHERE keyword IS NOT NULL AND is_active = true;
CREATE INDEX IF NOT EXISTS idx_question_approval_status ON public.question(approval_status);
CREATE INDEX IF NOT EXISTS idx_question_creator_approval ON public.question(creator_id, approval_status);
CREATE INDEX IF NOT EXISTS idx_question_approved_at ON public.question(approved_at DESC);

-- 질문 번들 관련 인덱스 (전문 검색 포함)
CREATE INDEX IF NOT EXISTS idx_qb_title ON public.question_bundle USING gin(to_tsvector('english', title));
CREATE INDEX IF NOT EXISTS idx_qb_description ON public.question_bundle USING gin(to_tsvector('english', description));
CREATE INDEX IF NOT EXISTS idx_qb_search ON public.question_bundle(title, description);

-- 사용자 관련 인덱스
CREATE INDEX IF NOT EXISTS idx_user_updated_at ON public."user"(updated_at DESC);

-- 게임 세션 관련 인덱스 (엔티티 @Index 어노테이션 반영)
CREATE INDEX IF NOT EXISTS idx_share_code ON public.game_session(share_code) 
    WHERE share_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_parent_session ON public.game_session(parent_session_id) 
    WHERE parent_session_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_game_session_temp_user ON public.game_session(temp_user_id) 
    WHERE temp_user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_game_session_player ON public.game_session(player_user_id);

-- 통계 관련 인덱스
CREATE INDEX IF NOT EXISTS idx_qstats_updated_at ON public.question_stats(updated_at DESC);

-- 번들-질문 매핑 인덱스
CREATE INDEX IF NOT EXISTS idx_bundle_question_order ON public.bundle_question(bundle_id, order_index);

-- 사용자 답변 관련 인덱스
CREATE INDEX IF NOT EXISTS idx_user_answer_session_id ON public.user_answer(session_id);

-- 3. 관리자 대시보드용 뷰 생성
-- =====================================================

-- 승인 대기 질문 통계 뷰
CREATE OR REPLACE VIEW v_pending_questions_stats AS
SELECT 
    COUNT(*) as total_pending,
    COUNT(DISTINCT creator_id) as unique_creators,
    DATE(created_at) as created_date
FROM question
WHERE approval_status = 'PENDING'
GROUP BY DATE(created_at)
ORDER BY created_date DESC;

-- 관리자 활동 통계 뷰
CREATE OR REPLACE VIEW v_admin_activity_stats AS
SELECT 
    u.nickname as admin_name,
    COUNT(CASE WHEN q.approval_status = 'APPROVED' THEN 1 END) as approved_count,
    COUNT(CASE WHEN q.approval_status = 'REJECTED' THEN 1 END) as rejected_count,
    DATE(q.approved_at) as activity_date
FROM question q
JOIN "user" u ON q.approved_by = u.user_id
WHERE q.approved_at IS NOT NULL
GROUP BY u.nickname, DATE(q.approved_at)
ORDER BY activity_date DESC;

-- 4. 유틸리티 함수 생성
-- =====================================================

-- 공유 코드 만료 처리 함수
CREATE OR REPLACE FUNCTION expire_old_share_codes()
RETURNS void AS $$
BEGIN
    UPDATE game_session
    SET share_code = NULL,
        share_code_created_at = NULL,
        share_code_expires_at = NULL
    WHERE share_code_expires_at < NOW()
    AND share_code IS NOT NULL;
END;
$$ LANGUAGE plpgsql;

-- 5. 기본 데이터 설정
-- =====================================================

-- 기본 관리자 계정 생성 (비밀번호: admin123을 BCrypt로 암호화)
INSERT INTO "user" (email, password, nickname, role, created_at, updated_at)
SELECT 
    'admin@balancegame.com',
    '$2a$10$8K1p/a/zPYp5.L8UG8pXOuLqE5LHG8TGY4YoFJ2mDVLHaKL9hTWmG',
    '시스템관리자',
    'ADMIN',
    NOW(),
    NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM "user" WHERE role = 'ADMIN'
);

-- 6. 테이블 코멘트 추가 (문서화)
-- =====================================================

COMMENT ON TABLE question IS '밸런스 게임 질문 테이블';
COMMENT ON COLUMN question.approval_status IS '질문 승인 상태: PENDING(대기), APPROVED(승인), REJECTED(거절)';
COMMENT ON COLUMN question.rejection_reason IS '거절 사유';
COMMENT ON COLUMN question.approved_by IS '승인/거절한 관리자 ID';
COMMENT ON COLUMN question.approved_at IS '승인/거절 일시';

COMMENT ON TABLE game_session IS '게임 세션 테이블 (개인/공유 플레이 지원)';
COMMENT ON COLUMN game_session.share_code IS '8자리 공유 코드';
COMMENT ON COLUMN game_session.share_code_created_at IS '공유 코드 생성 일시';
COMMENT ON COLUMN game_session.share_code_expires_at IS '공유 코드 만료 일시';
COMMENT ON COLUMN game_session.parent_session_id IS '비교 대상 원본 세션 ID';
COMMENT ON COLUMN game_session.temp_user_id IS '비회원 임시 식별자';
COMMENT ON COLUMN game_session.session_status IS '세션 상태: IN_PROGRESS, COMPLETED, EXPIRED';
COMMENT ON COLUMN game_session.completed_at IS '게임 완료 일시';

COMMENT ON TABLE user_answer IS '사용자 답변 기록 테이블';
COMMENT ON COLUMN user_answer.session_id IS '답변이 속한 게임 세션 ID';
COMMENT ON COLUMN user_answer.selected_option IS '선택한 옵션: A 또는 B';

-- 7. 초기화 완료 메시지
-- =====================================================

DO $$
BEGIN
    RAISE NOTICE '==============================================';
    RAISE NOTICE '밸런스 게임 시스템 데이터베이스 초기화 완료!';
    RAISE NOTICE '==============================================';
    RAISE NOTICE '생성된 구성 요소:';
    RAISE NOTICE '- 기본 테이블 9개 (엔티티와 완전 일치)';
    RAISE NOTICE '- 성능 최적화 인덱스 13개';
    RAISE NOTICE '- 관리자 대시보드 뷰 2개';
    RAISE NOTICE '- 유틸리티 함수 1개';
    RAISE NOTICE '- 기본 관리자 계정 1개';
    RAISE NOTICE '==============================================';
    RAISE NOTICE '수정된 사항:';
    RAISE NOTICE '- Question.approval_status 기본값 PENDING으로 변경';
    RAISE NOTICE '- GameSession에 completed_at, session_status 추가';
    RAISE NOTICE '- UserAnswer.selected_option을 VARCHAR(1)로 수정';
    RAISE NOTICE '- 불필요한 matching_score 컬럼 제거';
    RAISE NOTICE '==============================================';
    RAISE NOTICE '기본 관리자 계정:';
    RAISE NOTICE '  이메일: admin@balancegame.com';
    RAISE NOTICE '  비밀번호: admin123';
    RAISE NOTICE '==============================================';
END $$;